### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Isalenedean** [ankohanse/hass-dab-pumps#72]
**Describe the bug**
Config flow could not be loaded: {"message":"Invalid handler specified"}

**To Reproduce**
1. Go to '...' devices
2. Click on '....' add device
3. Scroll down to '....' dabpumps, click on it,
4. See error invalid handler

**Expected behavior**
Normaly the integration loads well

**Screenshots**

<img width="1210" height="834" alt="Image" src="https://github.com/user-attachments/assets/1d788e28-9562-4396-b99f-30b65973e86f" />

**iPad pro ipados26, please complete the following information):**
 - OS: [e.g. iOS] homeassistant os
 - Browser [e.g. chrome, safari] ios native haos app
 - Version [e.g. 22] core 2025.8.0

**Additional context**

After updating to 2025.8.0 integration was not loading.
1 deleted the intagration
2 removed from hacs
3 deleted all entities tied to dab
4 deleted everything tied to dab in .storage
5 restarted ha os
6 reinstalled through hacs
7 restart haos
8 add integration
9 error trying to add the integration

**Comment by avhove** [comment]
Same issue here. Current integration fails to load in HA 2025.8.0

```
Logger: homeassistant.config_entries
Source: config_entries.py:3760
First occurred: 9:45:45 PM (4 occurrences)
Last logged: 9:47:49 PM

Error occurred loading flow for integration dabpumps:
    cannot import name 'DabPumpsApiRightsError' from 'aiodabpumps'
    (/usr/local/lib/python3.13/site-packages/aiodabpumps/__init__.py)
```

and 

```
Logger: homeassistant.util.loop
Source: util/loop.py:137
First occurred: 9:45:45 PM (1 occurrence)
Last logged: 9:45:45 PM

Detected blocking call to import_module with args ('custom_components.dabpumps.config_flow',) 
inside the event loop by integration 'config' at 
homeassistant/components/config/config_entries.py, line 188: 
    return await super()._post_impl(request, data) 
(offender: /usr/src/homeassistant/homeassistant/loader.py, line 1292: 
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
), 
please create a bug report at:
    https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22 

For developers, please see:
    https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 156, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await self._post_impl(request, data)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 188, in _post_impl
    return await super()._post_impl(request, data)
```

Trying to set it up again, by adding a hub gives the error in a popup:
` {"message":"Invalid handler specified"}`

**Comment by avhove** [comment]
Update.
Editing the following line in the manifest.json file from
`"requirements": ["aiodabpumps>=0.1.24"],`

to
`"requirements": ["aiodabpumps>=0.1.24,<1.0.0"],`

seems to have solved the issue for me now.

**Comment by Isalenedean** [comment]
> Update. Editing the following line in the manifest.json file from `"requirements": ["aiodabpumps>=0.1.24"],`
> 
> to `"requirements": ["aiodabpumps>=0.1.24,<1.0.0"],`
> 
> seems to have solved the issue for me now.
 Yes indeed, it als worked for me!

**Comment by ankohanse** [comment]
Reopened the issue to make the solution of installing Dab Pumps integration version 2025.08.2 more visible...
